name = "rss-worker-2"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
no_bundle = true

# [build]
# command = "npm run build"
# cwd = "dist"
# watch_dir = "dist"
